config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]
  root to: "home#top"
  resources :books
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :profile_image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  has_many :books

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }, allow_blank: true
  # email不要
  validates :email, allow_blank: true, uniqueness: true

  # nameでログインできるように
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if name = conditions.delete(:name)
      where(conditions).where(["name = :value", { value: name }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?, except: [:show]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user) # ログイン後にユーザーの詳細ページへ
  end

  def after_sign_out_path_for(resource)
    root_path # ログアウト後にトップページへ
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :introduction, :profile_image])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    redirect_to books_path unless @book.user == current_user
  end

  def update
    @book = Book.find(params[:id])
    if @book.user == current_user
      if @book.update(book_params)
        redirect_to @book, notice: 'Book was successfully updated.'
      else
        render :edit
      end
    else
      redirect_to books_path
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.user == current_user
      @book.destroy
      redirect_to books_url, notice: 'Book was successfully destroyed.'
    else
      redirect_to books_path
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:top, :about]
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    redirect_to users_path unless @user == current_user
  end

  def update
    @user = User.find(params[:id])
    if @user == current_user
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.'
      else
        render :edit
      end
    else
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true, html: {class: "w-100"}) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control w-100" %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control w-100" %>
  </div>

  <div class="actions">
    <%= form.submit 'Update Book', class: "btn btn-primary w-100" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="sidebar">
        <%= render 'shared/user_info_sidebar', user: current_user %>
        <%= render 'shared/book_form_sidebar', book: @book %>
      </div>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Profile Image</th>
            <th>Title</th>
            <th>Body</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <% if book.user.profile_image.attached? %>
                  <%= link_to image_tag(book.user.profile_image.variant(resize: "50x50")), user_path(book.user) %><br>
                <% else %>
                  <%= link_to image_tag("no_image.jpg", size: "50x50"), user_path(book.user) %><br>
                <% end %>
                <%= link_to book.user.name, user_path(book.user) %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
              <td><%= link_to 'Edit', edit_book_path(book), class: 'btn btn-sm btn-success' %></td>
              <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: '本当に消しますか？' }, class: 'btn btn-sm btn-danger' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="sidebar">
        <%= render 'shared/user_info_sidebar', user: @book.user %>
        <%= render 'shared/book_form_sidebar', book: Book.new %>
      </div>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <p id="notice"><%= notice %></p>
      <table class="table">
        <tr>
          <td>
            <% if @book.user.profile_image.attached? && @book.user.profile_image.variable? %>
              <%= link_to user_path(@book.user) do %>
                <%= image_tag(@book.user.profile_image.variant(resize: "50x50")) %><br>
                <%= @book.user.name %>
              <% end %>
            <% elsif @book.user.profile_image.attached? %>
              <%= link_to user_path(@book.user) do %>
                <%= image_tag(@book.user.profile_image, size: "50x50") %><br>
                <%= @book.user.name %>
              <% end %>
            <% else %>
              <%= link_to user_path(@book.user) do %>
                <%= image_tag("no_image.jpg", size: "50x50") %><br>
                <%= @book.user.name %>
              <% end %>
            <% end %>
          </td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-sm btn-success' %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: 'btn btn-sm btn-danger' %></td>
          <% end %>
        </tr>
      </table>
      <%= link_to books_path, class: 'btn btn-outline-secondary mt-3' do %>
        <i class="fas fa-arrow-left"></i> Back
      <% end %>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<h1 style="text-align: center;">Welcome to <i class="fas fa-book"></i> <strong>Bookers!</strong></h1>
<p>This is an application where users can post and view book reviews.</p>

app/views/home/top.html.erb
<h1>Welcome to <i class="fas fa-book"></i> <strong>Bookers!</strong></h1>
<p>
  <%= link_to "Log in", new_user_session_path %> or
  <%= link_to "Sign up", new_user_registration_path %>
</p>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(model.errors.count, "error") %> prohibited this <%= model.class.name.underscore.humanize.downcase %> from being saved:</h2>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/4c39bb1393.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="bg-dark text-white shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand p-3" href="/" style="font-size:2rem; font-weight:bold;">
            Bookers
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                  aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-house"></i> Home'), user_path(current_user.id), class: 'nav-link text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-users"></i> Users'), users_path, class: 'nav-link text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-book-open"></i> Books'), books_path, class: 'nav-link text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-right-from-bracket"></i> Log out'), destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-house"></i> Home'), root_path, class: 'nav-link text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-link"></i> About'), home_about_path, class: 'nav-link text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-user-plus"></i> Sign up'), new_user_registration_path, class: 'nav-link text-white' %>
                </li>
                <li class="nav-item">
                  <%= link_to raw('<i class="fa-solid fa-right-to-bracket"></i> Log in'), new_user_session_path, class: 'nav-link text-white' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto container mt-4">
      <div class="row">
        <div class="col-md-12">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <%= yield %>
        </div>
      </div>
    </main>
    <footer class="bg-light text-dark pt-4 pb-4 mt-4">
      <div class="container">
        <div class="row">
          <div class="col-12 text-center">
            CopyRight Infratop.inc
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/shared/_book_form_sidebar.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title">New book</h2>
    <%= render 'shared/error_messages', resource: book %>
    <%= form_with model: book, scope: :book, local: true do |f| %>
      <div>
        <%= f.label :title %><br>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div>
        <%= f.label :body %><br>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <div>
        <%= f.submit 'Create Book', class: "btn btn-primary w-100" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= I18n.t("errors.messages.not_saved",
                   count: resource.errors.count,
                   resource: resource.class.model_name.human.downcase)
        %></h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_info_sidebar.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="card-title">User info</h2>
    <% if user %>
      <%= link_to edit_user_path(user) do %>
        <% if user.profile_image.attached? && user.profile_image.variable? %>
          <%= image_tag user.profile_image.variant(resize: "100x100"), size: "100x100", class: "img-fluid mb-3" %>
        <% elsif user.profile_image.attached? %>
          <%= image_tag user.profile_image, size: "100x100", class: "img-fluid mb-3" %>
        <% else %>
          <%= image_tag "no_image.jpg", size: "100x100", class: "img-fluid mb-3" %>
        <% end %>
      <% end %>
      <table class="table">
        <tr><th>name</th><th><%= user.name %></th></tr>
        <tr><th>introduction</th><th><%= user.introduction %></th></tr>
      </table>
      <% if user.id == current_user.id %>
        <%= link_to edit_user_path(user), class: 'btn btn-outline-secondary btn-block' do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>User Edit</h1>
<%= form_with model: @user, url: user_path(@user), method: :patch, local: true do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :profile_image %>
    <%= f.file_field :profile_image, accept: 'image/*', class: 'form-control-file' %>
  </div>
  <div class="form-group">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Update User', class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="sidebar">
        <%= render 'shared/user_info_sidebar', user: current_user %>
        <%= render 'shared/book_form_sidebar', book: Book.new %>
      </div>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Profile Image</th>
            <th>Introduction</th>
            <th colspan="2"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td>
                <% if user.profile_image.attached? %>
                  <%= image_tag user.profile_image.variant(resize: "50x50"), size: "50x50" %>
                <% else %>
                  <%= image_tag "no_image.jpg", size: "50x50" %>
                <% end %>
              </td>
              <td><%= user.introduction %></td>
              <td><%= link_to 'Show', user, class: 'btn btn-sm btn-primary' %></td>
              <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-sm btn-success' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="sidebar">
        <%= render 'shared/user_info_sidebar', user: @user %>
        <%= render 'shared/book_form_sidebar', book: Book.new %>
      </div>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Profile Image</th>
            <th>Title</th>
            <th>Body</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <% if book.user.profile_image.attached? && book.user.profile_image.variable? %>
                  <%= link_to image_tag(book.user.profile_image.variant(resize: "50x50")), user_path(book.user) %><br>
                <% else %>
                  <%= link_to image_tag("no_image.jpg", size: "50x50"), user_path(book.user) %><br>
                <% end %>
                <%= link_to book.user.name, user_path(book.user) %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
              <td><%= link_to 'Show', book, class: 'btn btn-sm btn-primary' %></td>
              <td><%= link_to 'Edit', edit_book_path(book), class: 'btn btn-sm btn-success' %></td>
              <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: '本当に消しますか？' }, class: 'btn btn-sm btn-danger' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to users_path, class: 'btn btn-outline-secondary mt-3' do %>
        <i class="fas fa-arrow-left"></i> Back to Users
      <% end %>
    </div>
  </div>
</div>